default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: mysql
  password: mysql
  host: db

development:
  <<: *default
  database: mysql_playground
